#! /usr/bin/env node

var raspInfo = require('raspberry-info');
var asyncq = require('async-q');
var clearScreen = require('cross-clear');
var isRoot = require('is-root');

if (!isRoot()) {
	console.log('Please sudo me!');
	process.exit();
}

var barChars = ' ▏▎▍▌▋▊▉█'.split('');

function drawBar(fraction, width) {
	if (fraction > 1) fraction = 1;
	
	var totalPx = width * barChars.length;
	var px = Math.round(fraction * totalPx);
	var chars = Math.floor(px/barChars.length);
	var detail = px%barChars.length;
	var remainder = width-chars-1;
	
	if (fraction < 1 && remainder >= 0) {
		return '[' + 
			barChars.slice(-1)[0].repeat(chars) + 
			barChars[detail] + 
			' '.repeat(remainder) +
		']  ';
	}
	else {
		return '[' + barChars.slice(-1)[0].repeat(width) + ']  ';
	}
}

function pad (txt, width) {
	txt = txt.replace(/\r|\n/g,'');
	if (width < txt.length) return txt;
	return txt + ' '.repeat(width - txt.length);
}

setInterval(function(){
	asyncq.parallel({
		cpuTemp: raspInfo.getCPUTemperature,
		gpuTemp: raspInfo.getGPUTemperature,
		memFree: raspInfo.getMemoryFree,
		memAvailable: raspInfo.getMemoryAvailable,
		memTotal: raspInfo.getMemoryTotal
	})
	.then(info => {
		cpuT = parseFloat(info.cpuTemp);
		gpuT = parseFloat(info.gpuTemp);
		mF = parseFloat(info.memFree)/1024;
		mA = parseFloat(info.memAvailable)/1024;
		mT = parseFloat(info.memTotal)/1024;
		mU = (mT-mA)/mT;
	
		clearScreen();
		console.log(
			`CPU Temp = ${pad(info.cpuTemp,8)}` + 
			drawBar(cpuT/80,10),
			new Date().toLocaleString()
		);
		console.log(
			`GPU Temp = ${pad(info.gpuTemp,8)}` + 
			drawBar(gpuT/80,10)
		);
		console.log(
			`Mem Use  = ${pad((mU*100).toFixed(1) + '%',8)}` + 
			drawBar(mU,10) +
			`(${pad(mF.toFixed(1),5)} MB free, ${pad(mA.toFixed(1),5)} MB available)`
		);
	});
},1000);

